###  user
POST  https://ngserver.herokuapp.com/user/
Content-Type: application/json

  {   
    "FirstName":" Ajay",
    "LastName":"sharma",
    "ImageUrl":"https://www.ImageUrl.com",
    "Email":"ajay@gmail.com",
    "password" :"123456"
 }


### dd
POST  https://ngserver.herokuapp.com/login/
Content-Type: application/json

  {   
    "FirstName":" Ajay",
    "LastName":"sharma",
    "ImageUrl":"https://www.ImageUrl.com",
    "Email":"ajay@gmail.com",
    "password" :"123456"
 }


###  user
GET  http://ngserver.herokuapp.com/user/
Content-Type: application/json
Authorization:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVlNjhiNWZjNWJlZDBjNmIxNThkNTYiLCJGaXJzdE5hbWUiOiIgQWpheSIsIkxhc3ROYW1lIjoic2hhcm1hIiwiSW1hZ2VVcmwiOiJodHRwczovL3d3dy5JbWFnZVVybC5jb20iLCJFbWFpbCI6ImFqYXlAZ21haWwuY29tIiwiX192IjowLCJpYXQiOjE2NjcxMzE2MzQsImV4cCI6MTY2NzE5MTYzNH0.tLThXs91XpS6V8jMezcCvA4sbET5gZwqeIWwMBmx3WE"

  {   
    "FirstName":" Ajay",
    "LastName":"sharma",
    "ImageUrl":"https://www.ImageUrl.com",
    "Email":"g.com",
    "password" :"123456"
 }


